/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup BetterflowAssets;
extern const Sifteo::AssetImage IconPeano;
extern const Sifteo::AssetImage IconBuddy;
extern const Sifteo::PinnedAssetImage BgTile;
extern const Sifteo::AssetImage IconSBOL;
extern const Sifteo::PinnedAssetImage StripeTile;
extern const Sifteo::AssetImage Tip0;
extern const Sifteo::AssetImage Tip1;
extern const Sifteo::AssetImage Tip2;
extern const Sifteo::AssetImage LabelChroma;
extern const Sifteo::AssetImage LabelPeano;
extern const Sifteo::AssetImage Footer;
extern const Sifteo::AssetImage LabelSandwich;
extern const Sifteo::AssetImage LabelBidirectional;
extern const Sifteo::AssetImage LabelBuddy;
extern const Sifteo::AssetImage LabelEmpty;
extern const Sifteo::AssetImage LabelCDS;
extern const Sifteo::AssetImage LabelChromoproteins;
extern const Sifteo::AssetImage LabelConsitutitive;
extern const Sifteo::AssetImage LabelConstitutiveProkaryoticRBS;
extern const Sifteo::AssetImage LabelEcoli;
extern const Sifteo::AssetImage LabelEukaryotic;
extern const Sifteo::AssetImage LabelFluorescentProteins;
extern const Sifteo::AssetImage LabelForward;
extern const Sifteo::AssetImage LabelMultiregulated;
extern const Sifteo::AssetImage LabelNegative;
extern const Sifteo::AssetImage LabelPositive;
extern const Sifteo::AssetImage LabelPromoters;
extern const Sifteo::AssetImage LabelRBS;
extern const Sifteo::AssetImage LabelReporters;
extern const Sifteo::AssetImage LabelReverse;
extern const Sifteo::AssetImage LabelRiboregulators;
extern const Sifteo::AssetImage LabelSelectionMarkers;
extern const Sifteo::AssetImage LabelTerminators;
extern const Sifteo::AssetImage LabelTransciptionalRegulators;
extern const Sifteo::AssetImage LabelYeast;
extern const Sifteo::AssetImage IconActivators;
extern const Sifteo::AssetImage IconBidirectional;
extern const Sifteo::AssetImage IconCDS;
extern const Sifteo::AssetImage IconChromoproteins;
extern const Sifteo::AssetImage IconConsitutitive;
extern const Sifteo::AssetImage IconConstitutiveProkaryoticRBS;
extern const Sifteo::AssetImage IconEcoli;
extern const Sifteo::AssetImage IconEukaryotic;
extern const Sifteo::AssetImage IconFluorescentProteins;
extern const Sifteo::AssetImage IconForward;
extern const Sifteo::AssetImage IconMultiple;
extern const Sifteo::AssetImage IconMultiregulated;
extern const Sifteo::AssetImage IconNegativePromoter;
extern const Sifteo::AssetImage IconPositivePromoter;
extern const Sifteo::AssetImage IconPromoter;
extern const Sifteo::AssetImage IconPromoterConstitutive;
extern const Sifteo::AssetImage IconRBS;
extern const Sifteo::AssetImage IconReporters;
extern const Sifteo::AssetImage IconRepressor;
extern const Sifteo::AssetImage IconReverse;
extern const Sifteo::AssetImage IconRiboregulators;
extern const Sifteo::AssetImage IconSelectionMarkers;
extern const Sifteo::AssetImage IconTerminator;
extern const Sifteo::AssetImage IconTranscriptionalRegulators;
extern const Sifteo::AssetImage IconYeast;
extern const Sifteo::AssetImage IconYeastRBS;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
