/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage LabelEmpty;
extern const Sifteo::AssetImage Icon;
extern const Sifteo::PinnedAssetImage StripeTile;
extern const Sifteo::PinnedAssetImage BgTile;
extern Sifteo::AssetGroup BetterflowAssets;
extern const Sifteo::AssetImage BG;
extern const Sifteo::AssetImage YG;
extern const Sifteo::AssetImage RG;
extern const Sifteo::AssetImage BCL;
extern const Sifteo::AssetImage BCB;
extern const Sifteo::AssetImage RCL;
extern const Sifteo::AssetImage RCR;
extern const Sifteo::AssetImage RCT;
extern const Sifteo::PinnedAssetImage WhiteTile;
extern const Sifteo::AssetImage BCR;
extern const Sifteo::AssetImage BCT;
extern const Sifteo::AssetImage YCL;
extern const Sifteo::AssetImage RCB;
extern const Sifteo::AssetImage YCR;
extern const Sifteo::AssetImage YCT;
extern const Sifteo::AssetImage YCB;
extern const Sifteo::AssetImage BFPlasmid;
extern const Sifteo::AssetImage RFPlasmid;
extern const Sifteo::AssetImage YFPlasmid;
extern const Sifteo::AssetImage Plasmid;
extern const Sifteo::AssetImage pcTop;
extern const Sifteo::AssetImage pcBot;
extern const Sifteo::AssetImage pcL;
extern const Sifteo::AssetImage pcR;
extern const Sifteo::AssetImage nul;
extern Sifteo::AssetGroup TestAssets;
extern const Sifteo::PinnedAssetImage Loop;
